- name: Add ppa
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: Install php
  apt: pkg={{ item }} state=latest
  with_items :
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-mysql
